config/routes.rb
Rails.application.routes.draw do
 root :to =>"nokogiri#index"
   resources :nokogiri

end

app/models/pandit.rb
class Pandit < ActiveRecord::Base
   
 def self.to_csv(file)
   CSV.generate do |csv|
     csv << ["Name","address","phone"]
     all.each do |f|
       csv << [f.name,f.address,f.phone]
     end
   end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/nokogiri_controller.rb
class NokogiriController < ApplicationController
  def index
    require 'json'
    require 'open-uri'
    require 'nokogiri'
    no =1
    @name = []
    @address=[]
    @phone =[]
   
    while true
      url = "http://www.justdial.com/functions/ajxsearch.php?national_search=0&act=pagination&city=Delhi+%2F+NCR&search=Pandits&where=Delhi+Cantt&catid=1195&psearch=&prid=&page=#{no}"
      json = JSON.parse(open(url).read) # make sure you check http errors here
      html = json['markup'] # can this field be empty? check for the json['error'] field
      doc = Nokogiri::HTML(html) # parse as you like
      c=  doc.css('span.jcn').collect {|node| node.text.strip}
      d=  doc.css('.jaid').collect {|node| node.text.strip}
      e=  doc.css('.jrcw').collect {|node| node.text.strip}
     break if no==10
      no+=1
      puts "==========#{@name}"
      c.each do |temp|
       @name << temp 
      end
      
      d.each do |temp|
       @address << temp 
      end
      
      e.each do |temp|
       @phone << temp 
       
      end
#       
      # @name << c
      # @address[no] << d
      # @phone[no] << e

    end
   
   respond_to do |format|
    format.html
    format.csv { send_data @name.to_csv(col_sep: "\t") }
     format.csv { send_data @address.to_csv(col_sep: "\t") }
    format.csv { send_data @phone.to_csv(col_sep: "\t") }
    format.xls

    end
   
# Define the css selectors to be used for extractions, most
end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nokogiri_helper.rb
module NokogiriHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataScraper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nokogiri/index.csv.erb
<h1 align="center">Records of All Pandits in Delhi/NCR</h1>
<% count1 = @name.count%>
<table class="table table-bordered">
	<tr>
		<th> Name </th>
		<th> address </th>
		<th> Phone </th>
	</tr>
	<%for i in 0..count1%>
<tr>
	
	<td>
		<%=@name[i]%>
	</td>
	<td>
		<%=@address[i]%>
	</td>
	<td>
		<%=@phone[i]%>
	</td>
</tr>
<%end%>

</table>

app/views/nokogiri/index.html.erb
<p>
  Download:
  <%= link_to "CSV", nokogiri_index_path(format: "csv") %> |
  <%= link_to "Excel", nokogiri_index_path(format: "xls") %>
</p>
<h1 align="center">Records of All Pandits in Delhi/NCR</h1>
<% count1 = @name.count%>
<table class="table table-bordered">
	<tr>
		<th> Name </th>
		<th> address </th>
		<th> Phone </th>
	</tr>
	<%for i in 0..count1%>
<tr>
	
	<td>
		<%=@name[i]%>
	</td>
	<td>
		<%=@address[i]%>
	</td>
	<td>
		<%=@phone[i]%>
	</td>
</tr>
<%end%>

</table>

app/views/nokogiri/index.xls.erb
<h1 align="center">Records of All Pandits in Delhi/NCR</h1>
<% count1 = @name.count%>
<table class="table table-bordered">
	<tr>
		<th> Name </th>
		<th> address </th>
		<th> Phone </th>
	</tr>
	<%for i in 0..count1%>
<tr>
	
	<td>
		<%=@name[i]%>
	</td>
	<td>
		<%=@address[i]%>
	</td>
	<td>
		<%=@phone[i]%>
	</td>
</tr>
<%end%>

</table>